server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8080/db_mblog?setUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/lib/


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info
    com.onetree.mapper: debug
    com:
      baomidou:
        mybatisplus:
          extension:
            spring: debug



